on: [push]

jobs:
  k6_local_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    container: docker://golang:1.17-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-counter binary
        run: xk6 build --with github.com/mstoykov/xk6-counter@latest

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ././test.js


 
